### ISSUE TITLE
Crashes with new forge version

### ISSUE THREAD

**Issue by Cheaterpaul** [maxanier/Guide-API#2]
GuideAPi: 1.16.1-2.2.0-alpha+20200716-0029
Forge: 32.0.93

Crashes on startup during AutomaticEventSubscriber with 
`java.lang.IllegalArgumentException: Method public static void de.maxanier.guideapi.RegistrarGuideAPI.registerModels(net.minecraftforge.client.event.ModelRegistryEvent) has @SubscribeEvent annotation, but takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent: class net.minecraftforge.client.event.ModelRegistryEvent`

**Comment by maxanier** [comment]
Doesn't seem to been an issue on Forge 1.16.4
